version: '3'
services:
  # DB
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - '3306:3306' #デバッグ用
    volumes:
      - ./sql:/docker-entrypoint-initdb.d"
      - ./sql/data:/var/lib/mysql
  
    environment:
      MYSQL_ROOT_PASSWORD: root

  # php
  php:
    container_name: "php"
    image: php:5.5-apache
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
      - ./share:/usr/share
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql